import type { SchemaType } from "./types"

export interface SchemaTemplate {
    id: string
    name: string
    description: string
    category: string
    type: SchemaType
    data: Record<string, unknown>
}

const today = () => new Date().toISOString().split("T")[0]

export const SCHEMA_TEMPLATES: SchemaTemplate[] = [
    // ── Content: Articles ─────────────────────────────────────────────────────
    {
        id: "blog-post",
        name: "Blog Post",
        description: "Standard blog post with author and publisher info",
        category: "Content",
        type: "BlogPosting",
        data: {
            headline: "My Blog Post Title",
            description: "A brief summary of the blog post content.",
            image: "https://example.com/blog-image.jpg",
            authorName: "Author Name",
            authorUrl: "https://example.com/author",
            datePublished: today(),
            dateModified: today(),
            publisherName: "My Website",
            publisherLogo: "https://example.com/logo.png",
            articleSection: "Blog",
        },
    },
    {
        id: "news-article",
        name: "News Article",
        description: "News article for press and media with dateline",
        category: "Content",
        type: "NewsArticle",
        data: {
            headline: "Breaking News Headline",
            description: "Summary of the news article.",
            image: "https://example.com/news-image.jpg",
            authorName: "Reporter Name",
            authorUrl: "https://example.com/reporter",
            datePublished: today(),
            publisherName: "News Organization",
            publisherLogo: "https://example.com/news-logo.png",
            articleSection: "News",
            dateline: "NEW YORK",
        },
    },
    {
        id: "tutorial-article",
        name: "Tutorial Article",
        description: "In-depth tutorial article with word count",
        category: "Content",
        type: "Article",
        data: {
            headline: "Complete Guide to Getting Started",
            description: "A comprehensive tutorial covering everything you need to know.",
            image: "https://example.com/tutorial.jpg",
            authorName: "Expert Author",
            authorUrl: "https://example.com/author",
            datePublished: today(),
            dateModified: today(),
            publisherName: "Tutorial Site",
            publisherLogo: "https://example.com/logo.png",
            articleSection: "Tutorials",
            wordCount: "3500",
        },
    },

    // ── Commerce: Products ────────────────────────────────────────────────────
    {
        id: "physical-product",
        name: "Physical Product",
        description: "Physical product listing with shipping and reviews",
        category: "Commerce",
        type: "Product",
        data: {
            name: "Product Name",
            description: "Detailed product description with key features.",
            image: "https://example.com/product.jpg",
            sku: "SKU-001",
            brand: "Brand Name",
            gtin: "0123456789012",
            price: "49.99",
            priceCurrency: "USD",
            availability: "https://schema.org/InStock",
            ratingValue: "4.5",
            ratingCount: "120",
            bestRating: "5",
            reviewCount: "85",
        },
    },
    {
        id: "digital-product",
        name: "Digital Product",
        description: "Digital download product (ebook, template, etc.)",
        category: "Commerce",
        type: "Product",
        data: {
            name: "Digital Product Name",
            description: "Premium digital product available for instant download.",
            image: "https://example.com/digital-product.jpg",
            brand: "Brand Name",
            price: "19.99",
            priceCurrency: "USD",
            availability: "https://schema.org/InStock",
            ratingValue: "4.8",
            ratingCount: "50",
            bestRating: "5",
        },
    },
    {
        id: "saas-product",
        name: "SaaS Product",
        description: "Software-as-a-Service product with subscription pricing",
        category: "Commerce",
        type: "SoftwareApplication",
        data: {
            name: "App Name",
            description: "A powerful SaaS tool that helps you accomplish tasks faster.",
            image: "https://example.com/app-icon.png",
            operatingSystem: "Web, Windows, macOS",
            applicationCategory: "BusinessApplication",
            price: "29",
            priceCurrency: "USD",
            ratingValue: "4.7",
            ratingCount: "500",
            bestRating: "5",
        },
    },

    // ── Content: FAQ ──────────────────────────────────────────────────────────
    {
        id: "faq-page",
        name: "FAQ Page",
        description: "Frequently asked questions for a support or help page",
        category: "Content",
        type: "FAQPage",
        data: {
            faqItems: [
                { question: "How do I get started?", answer: "Sign up for a free account and follow our quick-start guide." },
                { question: "What payment methods do you accept?", answer: "We accept Visa, Mastercard, American Express, and PayPal." },
                { question: "Can I cancel my subscription?", answer: "Yes, you can cancel anytime from your account settings." },
            ],
        },
    },

    // ── Local Business ────────────────────────────────────────────────────────
    {
        id: "restaurant",
        name: "Restaurant",
        description: "Restaurant with address, hours, cuisine, and price range",
        category: "Local",
        type: "Restaurant",
        data: {
            name: "Restaurant Name",
            description: "A cozy restaurant serving authentic cuisine.",
            telephone: "+1-555-123-4567",
            url: "https://example.com",
            servesCuisine: "Italian",
            priceRange: "$$",
            menuUrl: "https://example.com/menu",
            acceptsReservations: "true",
            streetAddress: "123 Main Street",
            addressLocality: "San Francisco",
            addressRegion: "CA",
            postalCode: "94102",
            addressCountry: "US",
            latitude: "37.7749",
            longitude: "-122.4194",
            openingHours: [
                { dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "11:00", closes: "22:00" },
                { dayOfWeek: ["Saturday", "Sunday"], opens: "10:00", closes: "23:00" },
            ],
        },
    },
    {
        id: "local-shop",
        name: "Local Shop",
        description: "Retail shop with address and hours",
        category: "Local",
        type: "LocalBusiness",
        data: {
            name: "Shop Name",
            description: "Your neighborhood store for quality products.",
            telephone: "+1-555-987-6543",
            url: "https://example.com",
            priceRange: "$$",
            streetAddress: "456 Oak Avenue",
            addressLocality: "Los Angeles",
            addressRegion: "CA",
            postalCode: "90001",
            addressCountry: "US",
            openingHours: [
                { dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], opens: "09:00", closes: "18:00" },
            ],
        },
    },
    {
        id: "professional-service",
        name: "Professional Service",
        description: "Professional service business (law, accounting, consulting)",
        category: "Local",
        type: "LegalService",
        data: {
            name: "Professional Service Firm",
            description: "Expert professional services for individuals and businesses.",
            telephone: "+1-555-456-7890",
            url: "https://example.com",
            priceRange: "$$$",
            streetAddress: "789 Business Blvd",
            addressLocality: "Chicago",
            addressRegion: "IL",
            postalCode: "60601",
            addressCountry: "US",
            openingHours: [
                { dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "08:00", closes: "17:00" },
            ],
        },
    },

    // ── Business / Organization ───────────────────────────────────────────────
    {
        id: "company-profile",
        name: "Company Profile",
        description: "Organization schema with logo, contact, and social profiles",
        category: "Business",
        type: "Organization",
        data: {
            name: "Company Name",
            description: "We build innovative solutions for modern businesses.",
            url: "https://example.com",
            logo: "https://example.com/logo.png",
            email: "hello@example.com",
            telephone: "+1-555-000-0000",
            contactType: "customer service",
            contactTelephone: "+1-555-000-0000",
            sameAs: [
                "https://twitter.com/company",
                "https://linkedin.com/company/company",
                "https://facebook.com/company",
            ],
        },
    },
    {
        id: "person-profile",
        name: "Person Profile",
        description: "Person schema for about pages and author profiles",
        category: "People",
        type: "Person",
        data: {
            name: "John Doe",
            jobTitle: "Senior Software Engineer",
            description: "Experienced developer specializing in web technologies.",
            url: "https://johndoe.com",
            image: "https://johndoe.com/photo.jpg",
            email: "john@example.com",
            worksForName: "Tech Company",
            worksForUrl: "https://techcompany.com",
            sameAs: [
                "https://twitter.com/johndoe",
                "https://linkedin.com/in/johndoe",
                "https://github.com/johndoe",
            ],
        },
    },

    // ── Events ────────────────────────────────────────────────────────────────
    {
        id: "tech-event",
        name: "Tech Event / Conference",
        description: "Event schema for conferences, workshops, and meetups",
        category: "Events",
        type: "Event",
        data: {
            name: "Annual Tech Conference 2026",
            description: "Join us for the biggest tech event of the year.",
            image: "https://example.com/event.jpg",
            startDate: "2026-06-15T09:00",
            endDate: "2026-06-17T18:00",
            eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
            eventStatus: "https://schema.org/EventScheduled",
            locationName: "Convention Center",
            locationAddress: "789 Event Blvd, San Francisco, CA",
            organizerName: "Tech Events Inc.",
            organizerUrl: "https://techevents.com",
            offerPrice: "299",
            offerCurrency: "USD",
            offerAvailability: "https://schema.org/InStock",
            offerUrl: "https://example.com/tickets",
        },
    },
    {
        id: "webinar",
        name: "Webinar / Online Event",
        description: "Online event schema for webinars and virtual meetups",
        category: "Events",
        type: "Event",
        data: {
            name: "Free Product Demo Webinar",
            description: "Join our live demo to see the product in action.",
            startDate: "2026-04-10T14:00",
            endDate: "2026-04-10T15:00",
            eventAttendanceMode: "https://schema.org/OnlineEventAttendanceMode",
            eventStatus: "https://schema.org/EventScheduled",
            locationUrl: "https://zoom.us/j/123456789",
            organizerName: "Company Name",
            offerPrice: "0",
            offerCurrency: "USD",
            offerAvailability: "https://schema.org/InStock",
        },
    },

    // ── Recipes ───────────────────────────────────────────────────────────────
    {
        id: "recipe-basic",
        name: "Recipe (Basic)",
        description: "Simple recipe with ingredients and instructions",
        category: "Content",
        type: "Recipe",
        data: {
            name: "Classic Chocolate Chip Cookies",
            description: "Soft and chewy chocolate chip cookies made from scratch.",
            image: "https://example.com/cookies.jpg",
            authorName: "Chef Name",
            prepTime: "PT15M",
            cookTime: "PT12M",
            totalTime: "PT27M",
            recipeYield: "24 cookies",
            recipeCategory: "Dessert",
            recipeCuisine: "American",
            calories: "150 calories",
            recipeIngredient: [
                "2 1/4 cups all-purpose flour",
                "1 tsp baking soda",
                "1 cup butter, softened",
                "3/4 cup sugar",
                "2 large eggs",
                "2 cups chocolate chips",
            ],
            recipeInstructions: [
                { name: "Mix dry ingredients", text: "Combine flour and baking soda in a bowl." },
                { name: "Cream butter and sugar", text: "Beat butter and sugar until light and fluffy." },
                { name: "Combine and bake", text: "Mix everything together, fold in chips, and bake at 375F for 9-11 minutes." },
            ],
        },
    },
    {
        id: "recipe-detailed",
        name: "Recipe (Detailed with Nutrition)",
        description: "Comprehensive recipe with full nutrition information",
        category: "Content",
        type: "Recipe",
        data: {
            name: "Grilled Salmon with Vegetables",
            description: "Healthy grilled salmon with seasonal roasted vegetables.",
            image: "https://example.com/salmon.jpg",
            authorName: "Chef Name",
            prepTime: "PT20M",
            cookTime: "PT25M",
            totalTime: "PT45M",
            recipeYield: "4 servings",
            recipeCategory: "Main Course",
            recipeCuisine: "Mediterranean",
            calories: "420 calories",
            fatContent: "22 g",
            carbohydrateContent: "15 g",
            proteinContent: "38 g",
            fiberContent: "4 g",
            sodiumContent: "380 mg",
            recipeIngredient: [
                "4 salmon fillets (6 oz each)",
                "2 tbsp olive oil",
                "1 lemon, juiced",
                "2 cups mixed vegetables",
                "Salt and pepper to taste",
            ],
            recipeInstructions: [
                { name: "Prepare salmon", text: "Season salmon with olive oil, lemon juice, salt, and pepper." },
                { name: "Prep vegetables", text: "Toss vegetables with olive oil and seasoning." },
                { name: "Grill", text: "Grill salmon skin-side down for 5-6 minutes per side. Grill vegetables alongside." },
                { name: "Serve", text: "Plate salmon over vegetables and garnish with fresh herbs." },
            ],
            ratingValue: "4.8",
            ratingCount: "125",
        },
    },

    // ── HowTo ─────────────────────────────────────────────────────────────────
    {
        id: "how-to-guide",
        name: "How-To Guide",
        description: "Step-by-step how-to guide with tools and supplies",
        category: "Content",
        type: "HowTo",
        data: {
            name: "How to Set Up Your New Website",
            description: "A complete guide to setting up a website from scratch.",
            image: "https://example.com/tutorial.jpg",
            totalTime: "PT1H",
            estimatedCost: "50 USD",
            supply: ["Domain name", "Hosting plan"],
            tool: ["Web browser", "Text editor"],
            steps: [
                { name: "Choose a domain", text: "Pick a domain name that represents your brand." },
                { name: "Select hosting", text: "Choose a reliable hosting provider." },
                { name: "Install CMS", text: "Set up your content management system." },
                { name: "Design your site", text: "Customize your theme and add content." },
                { name: "Launch", text: "Review everything and publish your site." },
            ],
        },
    },

    // ── Video ─────────────────────────────────────────────────────────────────
    {
        id: "video",
        name: "Video",
        description: "Video schema for YouTube or embedded video content",
        category: "Media",
        type: "VideoObject",
        data: {
            name: "Video Title",
            description: "A detailed description of the video content.",
            thumbnailUrl: "https://example.com/thumbnail.jpg",
            uploadDate: today(),
            duration: "PT10M30S",
            embedUrl: "https://www.youtube.com/embed/VIDEO_ID",
        },
    },

    // ── Podcast ───────────────────────────────────────────────────────────────
    {
        id: "podcast-episode",
        name: "Podcast Episode",
        description: "Podcast episode with series info and audio URL",
        category: "Media",
        type: "PodcastEpisode",
        data: {
            name: "Episode 42: The Future of AI",
            description: "In this episode, we discuss the latest developments in artificial intelligence.",
            url: "https://example.com/podcast/episode-42",
            datePublished: today(),
            duration: "PT45M",
            contentUrl: "https://example.com/podcast/episode-42.mp3",
            seriesName: "Tech Talk Podcast",
            seriesUrl: "https://example.com/podcast",
            episodeNumber: "42",
            seasonNumber: "2",
        },
    },

    // ── Education ─────────────────────────────────────────────────────────────
    {
        id: "online-course",
        name: "Online Course",
        description: "Online course with provider and pricing",
        category: "Education",
        type: "Course",
        data: {
            name: "Complete Web Development Bootcamp",
            description: "Learn web development from scratch with hands-on projects.",
            providerName: "Learning Platform",
            providerUrl: "https://example.com",
            url: "https://example.com/courses/web-dev",
            image: "https://example.com/course.jpg",
            instructorName: "Jane Smith",
            courseLanguage: "English",
            courseMode: "online",
            price: "49.99",
            priceCurrency: "USD",
            ratingValue: "4.7",
            ratingCount: "3200",
        },
    },

    // ── Jobs ──────────────────────────────────────────────────────────────────
    {
        id: "job-posting-remote",
        name: "Job Posting (Remote)",
        description: "Remote job listing with salary information",
        category: "Jobs",
        type: "JobPosting",
        data: {
            title: "Senior Software Engineer",
            description: "We're looking for an experienced software engineer to join our remote-first team.",
            datePosted: today(),
            validThrough: "2026-06-30",
            hiringOrganizationName: "Tech Company",
            hiringOrganizationUrl: "https://techcompany.com",
            employmentType: "FULL_TIME",
            remote: "true",
            addressCountry: "US",
            salaryValue: "150000",
            salaryMinValue: "130000",
            salaryMaxValue: "170000",
            salaryCurrency: "USD",
            salaryUnit: "YEAR",
            skills: ["TypeScript", "React", "Node.js", "PostgreSQL"],
        },
    },
    {
        id: "job-posting-onsite",
        name: "Job Posting (On-site)",
        description: "On-site job listing with location details",
        category: "Jobs",
        type: "JobPosting",
        data: {
            title: "Marketing Manager",
            description: "Seeking a creative marketing manager to lead our campaigns.",
            datePosted: today(),
            validThrough: "2026-05-31",
            hiringOrganizationName: "Agency Name",
            hiringOrganizationUrl: "https://agency.com",
            employmentType: "FULL_TIME",
            remote: "false",
            streetAddress: "100 Market St",
            addressLocality: "New York",
            addressRegion: "NY",
            postalCode: "10001",
            addressCountry: "US",
            salaryValue: "95000",
            salaryCurrency: "USD",
            salaryUnit: "YEAR",
        },
    },

    // ── Navigation ────────────────────────────────────────────────────────────
    {
        id: "breadcrumb-ecommerce",
        name: "E-Commerce Breadcrumb",
        description: "Product category breadcrumb trail",
        category: "Navigation",
        type: "BreadcrumbList",
        data: {
            breadcrumbs: [
                { name: "Home", url: "https://example.com" },
                { name: "Electronics", url: "https://example.com/electronics" },
                { name: "Phones", url: "https://example.com/electronics/phones" },
                { name: "iPhone 15", url: "https://example.com/electronics/phones/iphone-15" },
            ],
        },
    },

    // ── Reviews ───────────────────────────────────────────────────────────────
    {
        id: "product-review",
        name: "Product Review",
        description: "Individual product review with rating",
        category: "Content",
        type: "Review",
        data: {
            itemReviewedName: "Product Name",
            itemReviewedType: "Product",
            authorName: "Reviewer Name",
            ratingValue: "4",
            bestRating: "5",
            worstRating: "1",
            reviewBody: "This product exceeded my expectations. The quality is outstanding and it works exactly as described.",
            datePublished: today(),
        },
    },

    // ── Books ─────────────────────────────────────────────────────────────────
    {
        id: "book",
        name: "Book",
        description: "Book with author, ISBN, and publisher info",
        category: "Education",
        type: "Book",
        data: {
            name: "Book Title",
            description: "A compelling story about adventure and discovery.",
            image: "https://example.com/book-cover.jpg",
            authorName: "Author Name",
            isbn: "978-0-123456-78-9",
            numberOfPages: "320",
            bookFormat: "https://schema.org/Paperback",
            publisher: "Publisher Name",
            datePublished: "2025-01-15",
            inLanguage: "en",
            genre: "Fiction",
            ratingValue: "4.3",
            ratingCount: "850",
        },
    },

    // ── Software App ──────────────────────────────────────────────────────────
    {
        id: "software-app",
        name: "Software App",
        description: "Mobile or desktop application listing",
        category: "Commerce",
        type: "SoftwareApplication",
        data: {
            name: "My App",
            description: "A powerful app to boost your productivity.",
            image: "https://example.com/app-icon.png",
            operatingSystem: "iOS, Android",
            applicationCategory: "BusinessApplication",
            price: "0",
            priceCurrency: "USD",
            ratingValue: "4.6",
            ratingCount: "1200",
            bestRating: "5",
            downloadUrl: "https://example.com/download",
            softwareVersion: "2.1.0",
        },
    },

    // ── WebSite ───────────────────────────────────────────────────────────────
    {
        id: "website-search",
        name: "Website with Search",
        description: "Website schema with sitelinks search box",
        category: "Technical",
        type: "WebSite",
        data: {
            name: "My Website",
            url: "https://example.com",
            description: "The official website for My Brand.",
            searchActionTarget: "https://example.com/search?q={search_term_string}",
            searchActionQueryInput: "search_term_string",
        },
    },
]

export function getTemplatesByCategory(): Record<string, SchemaTemplate[]> {
    const grouped: Record<string, SchemaTemplate[]> = {}
    for (const template of SCHEMA_TEMPLATES) {
        if (!grouped[template.category]) {
            grouped[template.category] = []
        }
        grouped[template.category].push(template)
    }
    return grouped
}
